"""Pattern definitions for: ai_vocabulary"""

PATTERNS = [
    {
        "name": "ai_vocab_delved",
        "category": "ai_vocabulary",
        "regex": r'\bdelved\b',
        "cap": 0,
        "description": "AI vocabulary: delved",
    },
    {
        "name": "ai_vocab_tapestry",
        "category": "ai_vocabulary",
        "regex": r'\btapestry\s+of\b',
        "cap": 0,
        "description": "AI vocabulary: 'tapestry of' (figurative)",
    },
    {
        "name": "ai_vocab_testament",
        "category": "ai_vocabulary",
        "regex": r'\btestament\s+to\b',
        "cap": 0,
        "description": "AI vocabulary: 'testament to'",
    },
    {
        "name": "ai_vocab_palpable",
        "category": "ai_vocabulary",
        "regex": r'\bpalpable\b',
        "cap": 0,
        "description": "AI vocabulary: palpable",
    },
    {
        "name": "ai_vocab_ethereal",
        "category": "ai_vocabulary",
        "regex": r'\bethereal\b',
        "cap": 0,
        "description": "AI vocabulary: ethereal",
    },
    {
        "name": "ai_vocab_juxtaposition",
        "category": "ai_vocabulary",
        "regex": r'\bjuxtaposition\b',
        "cap": 0,
        "description": "AI vocabulary: juxtaposition",
    },
    {
        "name": "ai_vocab_ministrations",
        "category": "ai_vocabulary",
        "regex": r'\bministrations\b',
        "cap": 0,
        "description": "AI vocabulary: ministrations",
    },
    {
        "name": "ai_vocab_countenance",
        "category": "ai_vocabulary",
        "regex": r'\bcountenance\b',
        "cap": 0,
        "description": "AI vocabulary: countenance",
    },
    {
        "name": "ai_vocab_elicited",
        "category": "ai_vocabulary",
        "regex": r'\belicited\b',
        "cap": 0,
        "description": "AI vocabulary: elicited",
    },
    {
        "name": "ai_vocab_cascading",
        "category": "ai_vocabulary",
        "regex": r'\bcascad(?:ed|ing)\b',
        "cap": 0,
        "description": "AI vocabulary: cascaded/cascading (figurative)",
    },
    {
        "name": "ai_vocab_emboldened",
        "category": "ai_vocabulary",
        "regex": r'\bemboldened\b',
        "cap": 0,
        "description": "AI vocabulary: emboldened",
    },
    {
        "name": "ai_vocab_mosaic",
        "category": "ai_vocabulary",
        "regex": r'\bmosaic\s+of\b',
        "cap": 0,
        "description": "AI vocabulary: 'mosaic of'",
    },
    {
        "name": "ai_vocab_ephemeral",
        "category": "ai_vocabulary",
        "regex": r'\bephemeral\b',
        "cap": 0,
        "description": "AI vocabulary: ephemeral",
    },
    {
        "name": "ai_vocab_sublime",
        "category": "ai_vocabulary",
        "regex": r'\bsublime\b',
        "cap": 0,
        "description": "AI vocabulary: sublime (figurative)",
    },
    {
        "name": "ai_vocab_liminal",
        "category": "ai_vocabulary",
        "regex": r'\bliminal\b',
        "cap": 0,
        "description": "AI vocabulary: liminal",
    },
    {
        "name": "ai_vocab_ineffable",
        "category": "ai_vocabulary",
        "regex": r'\bineffable\b',
        "cap": 0,
        "description": "AI vocabulary: ineffable",
    },
    {
        "name": "ai_vocab_wistful",
        "category": "ai_vocabulary",
        "regex": r'\bwistful(?:ly)?\b',
        "cap": 1,
        "description": "AI vocabulary: wistful/wistfully (max 1)",
    },
    {
        "name": "ai_vocab_resonated",
        "category": "ai_vocabulary",
        "regex": r'\bresonat(?:ed|ing)\b',
        "cap": 0,
        "description": "AI vocabulary: resonated/resonating",
    },
    {
        "name": "ai_vocab_visceral",
        "category": "ai_vocabulary",
        "regex": r'\bvisceral(?:ly)?\b',
        "cap": 1,
        "description": "AI vocabulary: visceral/viscerally (max 1)",
    },
    {
        "name": "ai_vocab_poignant",
        "category": "ai_vocabulary",
        "regex": r'\bpoignant(?:ly)?\b',
        "cap": 1,
        "description": "AI vocabulary: poignant/poignantly (max 1)",
    },
    {
        "name": "ai_vocab_nuanced",
        "category": "ai_vocabulary",
        "regex": r'\bnuanced\b',
        "cap": 1,
        "description": "AI vocabulary: nuanced (max 1)",
    },
    {
        "name": "ai_vocab_hauntingly",
        "category": "ai_vocabulary",
        "regex": r'\bhauntingly\b',
        "cap": 0,
        "description": "AI vocabulary: hauntingly",
    },
]

COMBINED_CAP = None
